version: '3'
services:

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - app-network

  #MySQL database for tweets
  dbtweet:
    platform: linux/amd64
    image: mysql
    container_name: dbtweet
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: tweetdatabase
      MYSQL_ROOT_PASSWORD: MySecurePass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network


  #Backend Service for tweetApi
  tweet-api-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tweet-api-service
    restart: unless-stopped
    tty: true
    ports:
      - "8081:8081"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: backend
      SPRING_APPLICATION_NAME: tweet-api-service
      SERVER_PORT: 8081
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: mypass
      RABBITMQ_EXCHANGE: user_exchange
    volumes:
      - ./:/app
    networks:
      - app-network

  #Backend Service for userApi
  user-api-service:
    build:
      context: ../userapi
      dockerfile: ./Dockerfile
    container_name: user-api-service
    restart: unless-stopped
    tty: true
    ports:
      - "8082:8082"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: backenduser
      SPRING_APPLICATION_NAME: user-api-service
      SERVER_PORT: 8082
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: mypass
      RABBITMQ_EXCHANGE: user_exchange
    volumes:
      - ../userapi/:/app
    networks:
      - app-network

  react-app:
      build:
        context: ../frontend
        dockerfile: ./Dockerfile
        args:
          - REACT_APP_API_USER_URL=http://localhost:8082
          - REACT_APP_API_TWEET_URL=http://localhost:8081
      container_name: react-app
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
      environment:
        - REACT_APP_API_USER_URL=http://localhost:8082
        - REACT_APP_API_TWEET_URL=http://localhost:8081
      networks:
        - app-network
  auth-api-service:
    build:
      context: ../authapi
      dockerfile: ./Dockerfile
    container_name: auth-api-service
    restart: unless-stopped
    tty: true
    ports:
      - "8083:8083"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

